services:
    _defaults:
        autoconfigure: true
        autowire: false
        public: false

    Terminal42\FreshdeskTicketBundle\:
        resource: '../src/'

    Terminal42\FreshdeskTicketBundle\EventListener\FormListener:
        public: true
        arguments:
            $connection: '@database_connection'
            $projectDir: '%kernel.project_dir%'
